services:
  redis:
    image: redis:7
    container_name: redis
    ports:
     - "6379:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: aegisq-api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  worker:
    build: 
      context: .
      dockerfile: Dockerfile.worker
    container_name: aegisq-worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379